#!/bin/bash

# Custom banner
echo -e "\e[32m ▄████████ ███▄▄▄▄   ████████▄     ▄████████  ▄██████▄     ▄███████▄     ███     \e[39m"
echo -e "\e[32m ███    ███ ███▀▀▀██▄ ███   ▀███   ███    ███ ███    ███   ███    ███ ▀█████████▄ \e[39m"
echo -e "\e[32m ███    ███ ███   ███ ███    ███   ███    ███ ███    ███   ███    ███    ▀███▀▀██ \e[39m"
echo -e "\e[32m ███    ███ ███   ███ ███    ███  ▄███▄▄▄▄██▀ ███    ███   ███    ███     ███   ▀ \e[39m"
echo -e "\e[32m ▀███████████ ███   ███ ███    ███ ▀▀███▀▀▀▀▀   ███    ███ ▀█████████▀      ███     \e[39m"
echo -e "\e[32m ███    ███ ███   ███ ███    ███ ▀███████████ ███    ███   ███            ███     \e[39m"
echo -e "\e[32m ███    ███ ███   ███ ███   ▄███   ███    ███ ███    ███   ███            ███     \e[39m"
echo -e "\e[32m ███    █▀   ▀█   █▀  ████████▀    ███    ███  ▀██████▀   ▄████▀         ▄████▀   \e[39m"
echo ""
echo "Welcome to the Android Penetration Testing Tool Installer"
echo ""
echo -e "\033[33m----------------------------Author: Sh0r7Gi4n7---------------------------------------------\033[0m"
echo ""

# Define tools directory
tools_dir="$HOME/tools"

# Main menu
while true; do
  echo ""
  echo -e "\e[32m Please choose which tool(s) you would like to install: \e[39m"
  echo ""
  echo -e "\e[32m 1. APKtool \e[39m"
  echo -e "\e[32m 2. ADB \e[39m"
  echo -e "\e[32m 3. Drozer \e[39m"
  echo -e "\e[32m 4. Frida \e[39m"
  echo -e "\e[32m 5. MobSF \e[39m"
  echo -e "\e[32m 6. Quit \e[39m"
  echo ""
  read -p $'\e[32mEnter your choice [1-6]: \e[0m' choice
  echo ""

  case $choice in
    "1")
      echo "Installing APKtool..."
      # Install dependencies
      sudo apt-get update
      sudo apt-get install -y default-jre
      # Download and install APKtool
      wget https://raw.githubusercontent.com/iBotPeaches/Apktool/master/scripts/linux/apktool -O /usr/local/bin/apktool
      wget https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.4.1.jar -O /usr/local/bin/apktool.jar
      chmod +x /usr/local/bin/apktool
      break
      ;;
    "2")
      echo "Installing ADB..."
      # Install dependencies
      sudo apt-get update
      sudo apt-get install -y android-tools-adb
      break
      ;;
    "3")
      echo "Installing Drozer..."
      # Install dependencies
      sudo apt-get update
      sudo apt-get install -y python3 python3-pip python3-dev build-essential libssl-dev libffi-dev
      # Download and install Drozer
      pip3 install drozer --user
      # Download and install Drozer agent
      wget https://github.com/FSecureLABS/drozer/releases/download/2.4.4/drozer-agent-2.4.4.apk -O drozer-agent.apk
      adb install drozer-agent.apk
      # Remove downloaded apk file
      rm drozer-agent.apk
      break
      ;;
    "4")
      echo "Installing Frida..."
      # Install dependencies
      sudo apt-get update
      sudo apt-get install -y python3-dev python3-pip
      # Download and install Frida
      pip3 install frida-tools
      # Download and install Frida server
      wget https://github.com/frida/frida/releases/download/14.2.18/frida-server-14.2.18-android-x86_64.xz -O frida-server.xz
      xz -d frida-server.xz
      chmod +x frida-server
      sudo mv frida-server /usr/local/bin/
      # Remove downloaded file
      rm frida-server.xz
      break
      ;;
    "5")
      echo "Installing MobSF..."
      # Install dependencies
      sudo apt-get update
      sudo apt-get install -y python3 python3-pip python3-dev libffi-dev libssl-dev git
      # Download and install MobSF
      git clone https://github.com/MobSF/Mobile-Security-Framework-MobSF.git $tools_dir/mobSF
      cd $tools_dir/mobSF
      pip3 install -r requirements.txt
      # Add execute permissions to manage.py
      chmod +x manage.py
      break
      ;;
    "6")
      echo "Exiting..."
      exit 0
      ;;
    *)
      echo "Invalid choice. Please enter a number from 1 to 6."
      ;;
  esac
done





